version: '3.9'

services:
  app:
    build: .
    container_name: skincare-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dermatology_center
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - JWT_SECRET=ThisIsMySuperSecretKeyForJWT1234567890a
      - JWT_EXPIRATION=86400000
      - SPRING_AI_OPENAI_API_KEY=your_openai_api_key
      - DEBUG=false
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dermatology_center
    ports:
      - "5433:5432"
    volumes:
      - postgres-skincare-data:/var/lib/postgresql/data

volumes:
  postgres-skincare-data:
