version: '3.9'

services:
  app:
    build: .
    container_name: skincare-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://dpg-d4a1pmjipnbc739c0sk0-a:5432/skincare_db_data
      - DATABASE_USERNAME=skincare_db_user
      - DATABASE_PASSWORD=DEFvzYrHy32kmPZwdktPX4KPWseTrIkG
      - JWT_SECRET=ThisIsMySuperSecretKeyForJWT1234567890a
      - JWT_EXPIRATION=86400000
      - OPENAI_API_KEY=your_openai_api_key
      - PORT=8080
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: skincare_db_user
      POSTGRES_PASSWORD: DEFvzYrHy32kmPZwdktPX4KPWseTrIkG
      POSTGRES_DB: skincare_db_data
    ports:
      - "5432:5432"
    volumes:
      - postgres-skincare-data:/var/lib/postgresql/data

volumes:
  postgres-skincare-data:
